{% set version = "2.7.8" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mapview
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/mapview_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/mapview/mapview_{{ version }}.tar.gz
  sha256: 2b6dbffaefe76661e728243ecaf5764e72d627955fd252b181756a5950f749c2

build:
  number: 1
  merge_build_host: true  # [win]
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.11.3
    - r-base64enc
    - r-brew
    - r-htmltools
    - r-htmlwidgets
    - r-lattice
    - r-leafem
    - r-leaflet >=2.0.0
    - r-leafpop
    - r-png
    - r-raster
    - r-satellite
    - r-scales >=0.2.5
    - r-sf
    - r-sp
    - r-svglite
    - r-uuid
    - r-viridislite
    - r-webshot
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.11.3
    - r-base64enc
    - r-brew
    - r-htmltools
    - r-htmlwidgets
    - r-lattice
    - r-leafem
    - r-leaflet >=2.0.0
    - r-leafpop
    - r-png
    - r-raster
    - r-satellite
    - r-scales >=0.2.5
    - r-sf
    - r-sp
    - r-svglite
    - r-uuid
    - r-viridislite
    - r-webshot

test:
  commands:
    - $R -e "library('mapview')"  # [not win]
    - "\"%R%\" -e \"library('mapview')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/mapview
  license: GPL (>= 3)
  license_file: LICENSE
  summary: Methods to view spatial objects interactively

extra:
  recipe-maintainers:
    - ocefpaf
