{% set version = '2.4.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mapview
  version: {{ version|replace("-", "_") }}

source:
  fn: mapview_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/mapview_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/mapview/mapview_{{ version }}.tar.gz
  sha256: c178af512728d101c5119cf97593f6349c109cc8771246c1e4c6a52824d7a93e

build:
  merge_build_host: True  # [win]
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.11.3
    - r-base64enc
    - r-brew
    - r-gdalutils
    - r-htmltools
    - r-htmlwidgets
    - r-lattice
    - r-leaflet
    - r-png
    - r-raster
    - r-satellite
    - r-scales >=0.2.5
    - r-sf
    - r-sp
    - r-svglite
    - r-uuid
    - r-viridislite
    - r-webshot
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.11.3
    - r-base64enc
    - r-brew
    - r-gdalutils
    - r-htmltools
    - r-htmlwidgets
    - r-lattice
    - r-leaflet
    - r-png
    - r-raster
    - r-satellite
    - r-scales >=0.2.5
    - r-sf
    - r-sp
    - r-svglite
    - r-uuid
    - r-viridislite
    - r-webshot

test:
  commands:
    - $R -e "library('mapview')"  # [not win]
    - "\"%R%\" -e \"library('mapview')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/mapview
  license: GPL (>= 3)
  license_file: LICENSE
  summary: Methods to view spatial objects interactively.

extra:
  recipe-maintainers:
    - ocefpaf
