{% set version = "2.11.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mapview
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mapview_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mapview/mapview_{{ version }}.tar.gz
  sha256: 8cb5acbf4f98ceb20de4d19a6575baed2972343e49184e46a6a021123277ca9d

build:
  number: 0
  noarch: generic
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-base64enc
    - r-htmltools
    - r-htmlwidgets
    - r-lattice
    - r-leafem
    - r-leaflet >=2.0.0
    - r-leafpop
    - r-png
    - r-raster
    - r-satellite
    - r-scales >=0.2.5
    - r-servr
    - r-sf
    - r-sp
    - r-webshot
  run:
    - r-base
    - r-base64enc
    - r-htmltools
    - r-htmlwidgets
    - r-lattice
    - r-leafem
    - r-leaflet >=2.0.0
    - r-leafpop
    - r-png
    - r-raster
    - r-satellite
    - r-scales >=0.2.5
    - r-servr
    - r-sf
    - r-sp
    - r-webshot

test:
  commands:
    - $R -e "library('mapview')"           # [not win]
    - "\"%R%\" -e \"library('mapview')\""  # [win]

about:
  home: https://github.com/r-spatial/mapview
  license: GPL-3.0-or-later
  summary: Quickly and conveniently create interactive visualisations of spatial data with or without background maps. Attributes of displayed features are fully queryable via pop-up windows. Additional functionality includes methods to visualise true- and false-color raster images and bounding boxes.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
