{% set version = "2.6.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mapview
  version: {{ version|replace("-", "_") }}

source:
  fn: mapview_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/mapview_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/mapview/mapview_{{ version }}.tar.gz
  sha256: 2b141a82ad4b6d2d9b684af68b1dda2d5f9823f8f6f00eac1b30663ce44c1ecd

build:
  merge_build_host: True  # [win]
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-rcpp
    - r-base64enc
    - r-brew
    - r-gdalutils
    - r-htmltools
    - r-htmlwidgets
    - r-lattice
    - r-leaflet
    - r-png
    - r-raster
    - r-satellite
    - r-scales >=0.2.5
    - r-sf
    - r-sp
    - r-viridislite
    - r-webshot
  run:
    - r-base
    - r-rcpp
    - r-base64enc
    - r-brew
    - r-gdalutils
    - r-htmltools
    - r-htmlwidgets
    - r-lattice
    - r-leaflet
    - r-png
    - r-raster
    - r-satellite
    - r-scales >=0.2.5
    - r-sf
    - r-sp
    - r-viridislite
    - r-webshot

test:
  commands:
    - $R -e "library('mapview')"  # [not win]
    - "\"%R%\" -e \"library('mapview')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/mapview
  license: GPL (>= 3)
  license_file: LICENSE
  summary: Methods to view spatial objects interactively.

extra:
  recipe-maintainers:
    - ocefpaf
