{% set version = '2.5.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mapview
  version: {{ version|replace("-", "_") }}

source:
  fn: mapview_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/mapview_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mapview/mapview_{{ version }}.tar.gz
  sha256: ee565f2facd64a648a73fa3f8ad8d9862d2fdc1858bf5038d27cec4ecb9d2c58

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcpp >=0.11.3
    - r-base64enc
    - r-brew
    - r-htmltools
    - r-htmlwidgets
    - r-lattice
    - r-leaflet >=1.0.0
    - r-png
    - r-raster
    - r-satellite
    - r-scales >=0.2.5
    - r-sf
    - r-sp
    - r-stars
    - r-svglite
    - r-uuid
    - r-viridislite
    - r-webshot
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.11.3
    - r-base64enc
    - r-brew
    - r-htmltools
    - r-htmlwidgets
    - r-lattice
    - r-leaflet >=1.0.0
    - r-png
    - r-raster
    - r-satellite
    - r-scales >=0.2.5
    - r-sf
    - r-sp
    - r-stars
    - r-svglite
    - r-uuid
    - r-viridislite
    - r-webshot

test:
  commands:
    - $R -e "library('mapview')"           # [not win]
    - "\"%R%\" -e \"library('mapview')\""  # [win]

about:
  home: https://github.com/r-spatial/mapview
  license: GPL (>= 3) | file LICENSE
  summary: 'Quickly and conveniently create interactive visualisations of spatial data with or
    without background maps. Attributes of displayed features are fully queryable via
    pop-up windows. Additional functionality includes methods to visualise true- and
    false-color raster images, bounding boxes, small multiples and 3D raster data cubes. '
  license_family: GPL3

extra:
  recipe-maintainers:
    - ocefpaf
