appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: JC5fMWmblZNXuk+yNUQ85UngYX4FSUfsbl3w7Yo5n9LsearSY/hADpR3bIhnFwdmAe+TQkklp+bh1EDyaSnqCr0CdEtJGCspR2ymbwMgkA0TmPPb3Hc/xMk/G+vuVJ5B9qZkh/5J2FqtHTkotlW7gBZN+ro+qj/KTLtJQeUf9RXCqKHCoc2ZeAvg48v47p3sNhAD4kr2qs+QdckGYcdMHIDQLri/LQm9iuPsYDmy8yJbK4JarJEEJv5aZ2fvCUc+eBWZC6yEy1nvfzt+7l+2uneBrxUNB6sWF4H2liRsgoLCe9LP+hjPUm+TYpQSGnXrrcOPKlDs4LlYQG0tWeb+0TWe3SKJ9EuCxjYQn+BIzFDfsM1ZieiI+BZJuU9SEnbpMWO8SfPuDVA3v1D967IWMROFtb5bGmNJhJockpfdfAiTrGtUp3O3fT5b9lXCPWXq18iaOMPJh03G3jt6zzcVpE0Vl6DpF8rslp6vjjLTszv2y5UJzVtzwb7K9PuY4lqkchHiDs8dpHENsoXnynEfpPBMwwAAa0E5U1O2rBvj5v9FDv3DYoDF/nWAFiWgf/gCI6h9PtyzXz2qFdDjpuSBA+6HG13A9sjHye0p50oBW+4kSN7PrEPqzvpjExxOqAJydi5U2REQ0DhqXE7l9GZhd7TugT7q5ECCo/Qbx02SXgk=
